spring:
   application:
      name: picpay_clone
   datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/picpay_clone
      username: postgres
      password: secret
      initialization-mode: always
   api:
      versao: 1.0.0
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
      
logging:
   level:
      web: TRACE
l     org:
         springframework:
            web: TRACE