spring:
   application:
      name: picpay_clone
   datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/picpay_clone
      username: postgres
      password: secret
      initialization-mode: always
   api:
      versao: 1.0.0
# JPA properties
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
   cache:
      type: redis
   redis:
      host: localhost
      port: 6379

#JWT
picpayclone:
   jwt:
      expiration: 86400000
      secretKey: secret12345qwert!@
            
logging:
   level:
      web: TRACE
      org:
         springframework:
            web: TRACE
            
# Actuator
management:
   endpoint:
      health:
         show-details: always
      web:
         exposure:
            include: '*'
info:
   app:
      name: '@project.name@'
      version: '@project.version@'

   